snd-soc-adi-axi-i2s-objs := axi-i2s.o
snd-soc-adi-axi-spdif-objs := axi-spdif.o
snd-soc-zybo-ssm2603-objs := zybo_ssm2603.o

obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o
obj-$(CONFIG_SND_SOC_ZYBO_SSM2603) += snd-soc-zybo-ssm2603.o
